### ISSUE TITLE
Create image_element.php

### ISSUE THREAD

**Issue by pdtynan** [CodeForTucson/wizardmaker#16]
The present file is just a stub.  See the spec at https://drive.google.com/drive/folders/0B-aMzFGhQdHZSjQ0Z3h5T3FWRXM?usp=sharing.

**Comment by pdtynan** [comment]
I have changed the spec and flow on this. Also, I thought my iPhone might give me the option of video or image or from the gallery but I'm not seeing it yet.  This will take some research or input from a real programmer.

**Comment by pdtynan** [comment]
Also, I have not figured out how to get pictures from the iPhone photo gallery.  And I don't have an Android phone to test.

**Comment by pdtynan** [comment]
I have commited code that does not work in case anyone wants to look at it. I can take the picture on my iPhone 5 but when I update all goes blank.

**Comment by pdtynan** [comment]
Thinking about this I decided to do a simple upload first.  Also, I notice, with the new IOS, that I can edit pictures and clip video on my phone.  But I don't seem to be able to do this when I call up the camera in the web app.  So maybe it is better to tell the user to just take pictures and video, edit them on their phone or on their lap top, and then either get them from the device gallery or upload them from the camera.  So when they want to put in an image, I will put a placesaver with the description of the image and later they can replace it.

**Comment by DainialPadraig** [comment]
https://coderwall.com/p/epwmoa/html5-mobile-device-camera-access

**Comment by pdtynan** [comment]
Thanks Dan.  When I try this on my iPhone 5 I can take a picture but I can't edit it nor can I select from the gallery. But I have not experimented with this much yet.  But if I could edit, I don't see a way of down sampling the image on my phone so the the image will be big. 

But as I thought about it and realized that the user has to lots of other things on a laptop (like write a lot of text) I thought I would have them put in a text placeholder when on the phone and they could replace it with an image later. Now they can play with images, annotate them, select the best one from a set, etc. 

After I get that to work I will go back and think about adding the option of direct capture to see if it is feasible.  Here is a flow chart of what I am working on.  I will update the spec eventually. I have not pushed a version of this new code to git as I am in an early stage.
[Get pictures or video.pdf](https://github.com/CodeForTucson/wizardmaker/files/1375779/Get.pictures.or.video.pdf)

**Comment by pdtynan** [comment]
OK, commited this though users can only upload from a laptop or desktop.  Maybe this is best because users can lighten and edit the material.  I'll open an issue regarding streaming to be considered later
