### ISSUE TITLE
Research best method to test storyboards

### ISSUE THREAD

**Issue by meiqimichelle** [CodeForTucson/wizardmaker#3]
We want to put the storyboards from #2 in front of someone trying to explain something as soon as possible. We should investigate options for this. Perhaps InVision or similar clickable prototype.

**Comment by pdtynan** [comment]
It seems from our last meeting of 2/21 that we decided we should have some interviews first with some of our target organizations. I suggested that the interviews could be in two phases where first we speak generally about the issue and their pain points and in the second phase we might show them a storyboard or click thru prototype.
I have posted a short plan for this on the Google drive called WizardMaker Field Study Plan V1.  Let me know what you think. We are not ready to do the interviews as we do not have the phase 2 materials ready yet.
